[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/xkBase/*"
  to = "/xkBase/index.html"
  status = 200

[[redirects]]
  from = "/xkBase"
  to = "/xkBase/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
